#!/usr/bin/env sh

exec env -u DISPLAY /usr/bin/Xvfb :0.0 \
    -nocursor \
    -noreset \
    +extension COMPOSITE \
    +extension DAMAGE \
    +extension DOUBLE-BUFFER \
    +extension GLX \
    +extension RANDR \
    +extension X-Resource \
    +extension XFIXES \
    +extension XVideo \
    +extension XVideo-MotionCompensation
